### PR TITLE
Session 3

### PR DESCRIPTION
**Pull request by dac2229**

### CODE REVIEW

**Comment by ldconejo** [comment]
Hi Daniel,

On _list_lab.py_ you can simplify the condition for this _while_ loop:

```
    while response4 != 'yes' and response4 != 'no':
        response4 = input(f'Do you like {value.lower()}?')
```

It could be turned into:

```
    while response4 not in ('yes', 'no'):
        response4 = input(f'Do you like {value.lower()}?')
```

This also has the advantage of being extensible to many more options that could be easily configured. For example:

```
    VALID_RESPONSES = ('yes', 'no', 'maybe')
    while response4 not in VALID_RESPONSES:
        response4 = input(f'Do you like {value.lower()}?')
```

-Luis

**Comment by ldconejo** [comment]
Hi Daniel,

Great job on the String Formatting Exercise. One thing to avoid is redefining built-in elements by using them as variable names. In your case, you did that with _tuple_ and _format_. Python will let you, but you'll lose the functionality of those built-in elements and break any code that uses them within the context in which they were redefined.

-Luis

**Comment by ldconejo** [comment]
Hi Daniel,

For the slicing lab, you're missing one requirement on this one:

_with the first 4 and the last 4 items removed, and then every other item in the remaining sequence_

Once the first/last 4 items have been removed, you need to also leave out every other item in the remaining sequence.

-Luis

**Comment by ldconejo** [comment]
Hi Daniel,

There are quite a few changes to be made for the mailroom assignment.

1. Enable a main menu with at least three options: "Report", "Send thank you (add donation)", "Exit".
2. "Report" should show a list of donors, total donations and number of donations. Your code is already able of doing this.
3. "Send thank you" should prompt the user for three possible things: The name of a user who's already in the database, the name of a new donor, the word "list", which would make it show a list of existing donors.

After "Report" or after "Send thank you", you should always return to the main menu, instead of exiting right away. This would make it possible to check that new donors/donations have been effectively added to the database.

4. Setup your donor database as a dictionary, something like this:

```
donors = {'art lang': [1000, 435], 'harry scary': [50], 'jigga boo': [1000, 50, 50000]}
```

Please resubmit your assignment once these changes have been incorporated and we will update your grade.

Regards,

Luis

**Comment by ldconejo** [comment]
Closing this pull request while updated code (and potentially submissions for lesson 4) are added.

-Luis

**Comment by dac2229** [comment]
Luis,

I had a question about GitHub. How come when I go here I don't see my name?
https://github.com/UWPCE-PythonCert-ClassRepos/GP_Python210B_Winter_2019/tree/master/students

And when I go here I can only see my name and two other folders and none of
the other student folders?
https://github.com/dac2229/GP_Python210B_Winter_2019

It also says I'm This branch is 18 commits ahead, 436 commits behind
UWPCE-PythonCert-ClassRepos:master. and I don't know why.

Thanks,
Daniel C.

**Comment by ldconejo** [comment]
Hi Daniel,

Good question. Since there were quite few changes requested for the code you submitted, your pull request was closed instead of merged into the main repository. That means the code you submitted hasn't become part of the main repository yet, which is why your folder doesn't show up there yet.

The second link you're showing is that of your fork of the repository, which is the copy you manage (for example, you can commit code directly to your fork, but you cannot do a direct commit to the main repository, you have to do it as a pull request). 

On the third thing you mention (commits ahead and commits behind), you need to update and merge your fork with the main repository (and do this regularly, to stay in sync). Your fork right now is most likely a copy of the main repository as it was when you first created the fork, plus the changes you have been committing (those are the 18 commits). But your classmates have also been making commits, some of those commits have already been accepted as pull requests into the main repository (those are the 436 behind).

Run the following commands from a terminal window on your fork sync it with the main repository:

```
git fetch upstream
git merge upstream/master
```

If you get an error stating you haven't defined an upstream, run this command:

```
git remote add upstream https://github.com/UWPCE-PythonCert-ClassRepos/GP_Python210B_Winter_2019.git 
```
Regards,

Luis

**Comment by dac2229** [comment]
I tried that before and I get the same results.
Daniels-MacBook-Pro:GP_Python210B_Winter_2019 Daniel$ git fetch upstream

Daniels-MacBook-Pro:GP_Python210B_Winter_2019 Daniel$ git merge
upstream/master

Already up to date.

Daniels-MacBook-Pro:GP_Python210B_Winter_2019 Daniel$ git remote add
upstream
https://github.com/UWPCE-PythonCert-ClassRepos/GP_Python210B_Winter_2019.git


fatal: remote upstream already exists.

Daniels-MacBook-Pro:GP_Python210B_Winter_2019 Daniel$ git merge
upstream/master

Already up to date.

Daniels-MacBook-Pro:GP_Python210B_Winter_2019 Daniel$ ls

README.md examples solutions students

Daniels-MacBook-Pro:GP_Python210B_Winter_2019 Daniel$ cd students

Daniels-MacBook-Pro:students Daniel$ ls

00-README.md daniel_carrasco example_student jesse_miller

Daniels-MacBook-Pro:students Daniel$

**Pull request closed without merging**
