### PR TITLE
Turning in lesson 03 assignments: list lab, slicing lab, string formatting lab, and mailroom pt. 1

### PR DESCRIPTION
**Pull request by jroam142**

### CODE REVIEW

**Comment by ldconejo** [comment]
All requirements met for the List Lab part.

-Luis

**Comment by jroam142** [comment]
It looks like my commits are showing up here under your comment. Do I need to make another pull request now that I fixed that issue?

**Comment by ldconejo** [comment]
Hi Jeremy,

No, that's ok. I can see the updated code now.

Regards,

Luis

**Comment by ldconejo** [comment]
All requirements for the slicing lab are met.

-Luis

**Comment by ldconejo** [comment]
Hi Jeremy,

Good job on the mailroom assignment.

-Luis

**Comment by ldconejo** [comment]
Merging pull request as all related work has already been reviewed.

**Pull request merged**
