### PR TITLE
One last question

### PR DESCRIPTION
**Pull request by UncleanlyCleric**
Hopefully this will be my last question, I'm getting a key error when using mail_box.py mail_send and I can't figure out why this works in cli_main.py print_report but not here.

### CODE REVIEW

**Comment by UncleanlyCleric** [comment]
DB looks right:
     
{'Robert Smith': <donor_models.DonorTools object at 0x10df19550>, 'JD Cronise': <donor_models.DonorTools object at 0x10df19d68>, 'Chris Stapleton': <donor_models.DonorTools object at 0x10df24588>, 'Dave Lombardo': <donor_models.DonorTools object at 0x10df245c0>, 'Randy Blythe': <donor_models.DonorTools object at 0x10df245f8>, 'Devin Townsand': <donor_models.DonorTools object at 0x10df24630>, 'Kerry Miller': <donor_models.DonorTools object at 0x10ddefe80>}

**Comment by UncleanlyCleric** [comment]
Note, that when I got the KeyError the DB was completely empty.

**Comment by UncleanlyCleric** [comment]
It's almost like it's being added to a different DB...

**Comment by UncleanlyCleric** [comment]
Fixed!  Submitting!

**Comment by ldconejo** [comment]
Hi Jesse,

Trying to send a thank you note to a single donor causes the following error:

```
Traceback (most recent call last):
  File "mailroom_oo.py", line 8, in <module>
    Menus.main()
  File "/Users/ldconejo/Documents/UW/GP_Python210B_Winter_2019/GP_Python210B_Winter_2019/students/jesse_miller/session09/cli_main.py", line 193, in main
    Menus.menu_choice[response]()
  File "/Users/ldconejo/Documents/UW/GP_Python210B_Winter_2019/GP_Python210B_Winter_2019/students/jesse_miller/session09/cli_main.py", line 73, in donor_mail_choice
    MailBox.mail_send(donor_tools, donor)
  File "/Users/ldconejo/Documents/UW/GP_Python210B_Winter_2019/GP_Python210B_Winter_2019/students/jesse_miller/session09/mail_box.py", line 53, in mail_send
    MailBox.mail_format(donor_tools[donor].name, \
TypeError: 'DonorTools' object is not subscriptable
```

**Comment by UncleanlyCleric** [comment]
That.   Huh.   Okay on it.

**Comment by UncleanlyCleric** [comment]
Well.  Will be on it when my power comes back.

**Pull request merged**
