### PR TITLE
Adding lesson 3 assignment files

### PR DESCRIPTION
**Pull request by sdlipp**
Lesson 3 Assignment Files:

- Mailroom, Part 1

- Slicing Lab

- String Formatting Lab

- List Lab

### CODE REVIEW

**Comment by ldconejo** [comment]
Hi Scott,

For the List Lab, the final requirement is to have the letters on each of the items (fruits, in this case) reversed (for example, _Apples_ becomes _selppA_). Please correct that a resubmit your code. Everything else on the List Lab looks good.

Regards,

Luis

**Comment by sdlipp** [comment]
Thanks Luis.  The requested changes to list_lab should be committed now

**Comment by ldconejo** [comment]
Hi Scott,

The List Lab looks great. Some things to consider for future assignments is to limit both comment and code lines to less than 100 characters (to improve readability) and simplify complex conditions like this one:

```
if not (user_response == "no" or user_response == "yes"):
```

Which could be changed to:

```
if user_response not in ("yes", "no"):
```
This has the advantage of being easily extensible to more options by simply changing the tuple of valid options.

Keep up the good work!

Luis

**Comment by ldconejo** [comment]
All requirements met for the Slicing Lab.

**Comment by ldconejo** [comment]
Hi Scott,

Good job on the mailroom assignment, all requirements are met. Whenever possible, try to limit your code/comments to less than 100 characters (to improve readability). Also, when you split line (a great way to avoid the 100-character limit) watch for proper indentation:

```
    donation_amount = input("Please enter the donation amount (or enter 'Quit' to return to "
                                "Main Menu): ").strip("$")
```

Should be:
```
    donation_amount = input("Please enter the donation amount (or enter 'Quit' to return to "
                            "Main Menu): ").strip("$")
```

Keep up the good work,

Luis

**Pull request merged**
