### PR TITLE
Adding for Lesson 3

### PR DESCRIPTION
**Pull request by woosukjeung**
having a bit of problem with the List Exercise where the computer would freeze upon loading causing the delay in submission cause i had to fix my computer first

### CODE REVIEW

**Comment by woosukjeung** [comment]
added fixed list assignment

**Comment by ldconejo** [comment]
Hi Wooseok, 

For the List Lab, when you're locating items in the fruit list by number, one of the requirements is that you consider the first element of the list of fruits to be index 1, while Python indexes lists by starting at 0. Please correct that.

For Series 2, also in the List Lab, you're asking the user to select a fruit to delete but you're not executing the deletion.

Regards,

Luis

**Comment by ldconejo** [comment]
Hi Wooseok,

Great work on the string formatting exercise! One thing to consider is to use enumeration when going through the elements of a list or tuple. For example:

```
    for i in range(len(tuple_to_format)):
        print('%10s, %3d,  $%9.2f' % tuple_to_format[i])
```

Could be turned into this:

```
    for element in tuple_to_format:
        print('%10s, %3d,  $%9.2f' % element)
```

Regards,

Luis

**Comment by ldconejo** [comment]
All assignment requirements met for the Slicing Lab.

**Pull request merged**
