### PR TITLE
Submitting html_render assignment

### PR DESCRIPTION
**Pull request by Douglas-Klos**

### CODE REVIEW

**Comment by Douglas-Klos** [comment]
Indentation is working perfectly on my end, can you be more specific please?

**Comment by mdgregor** [comment]
This is the output I get when running yours:
```/home/ferros/PycharmProjects/uw2019/venv/bin/python /home/ferros/PycharmProjects/uw2019/doug/run_html_render.py
<html>
Here is a paragraph of text -- there could be more of them, but this is enough  to show that we can do some text
And here is another piece of text -- you should be able to add any number
</html>

<!DOCTYPE html>
<html>
<body>
<p>
Here is a paragraph of text -- there could be more of them, but this is enough  to show that we can do some text
</p>
<p>
And here is another piece of text -- you should be able to add any number
</p>
</body>
</html>

<!DOCTYPE html>
<html>
<head>
<title>PythonClass = Revision 1087:</title>
</head>
<body>
<p>
Here is a paragraph of text -- there could be more of them, but this is enough  to show that we can do some text
</p>
<p>
And here is another piece of text -- you should be able to add any number
</p>
</body>
</html>

<!DOCTYPE html>
<html>
<head>
<title>PythonClass = Revision 1087:</title>
</head>
<body>
<p style="text-align: center; font-style: oblique;">
Here is a paragraph of text -- there could be more of them, but this is enough  to show that we can do some text
</p>
</body>
</html>

<!DOCTYPE html>
<html>
<head>
<title>PythonClass = Revision 1087:</title>
</head>
<body>
<p style="text-align: center; font-style: oblique;">
Here is a paragraph of text -- there could be more of them, but this is enough  to show that we can do some text
</p>
<hr />
</body>
</html>

<!DOCTYPE html>
<html>
<head>
<title>PythonClass = Revision 1087:</title>
</head>
<body>
<p style="text-align: center; font-style: oblique;">
Here is a paragraph of text -- there could be more of them, but this is enough  to show that we can do some text
</p>
<hr />
And this is a 
<a href="http://google.com">link</a>
to google
</body>
</html>

<!DOCTYPE html>
<html>
<head>
<title>PythonClass = Revision 1087:</title>
</head>
<body>
<h2>PythonClass - Class 6 example</h2>
<p style="text-align: center; font-style: oblique;">
Here is a paragraph of text -- there could be more of them, but this is enough  to show that we can do some text
</p>
<hr />
<ul id="TheList" style="line-height:200%">
<li>
The first item in a list
</li>
<li style="color: red">
This is the second item
</li>
<li>
And this is a 
<a href="http://google.com">link</a>
to google
</li>
</ul>
</body>
</html>

<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8" />
<title>PythonClass = Revision 1087:</title>
</head>
<body>
<h2>PythonClass - Example</h2>
<p style="text-align: center; font-style: oblique;">
Here is a paragraph of text -- there could be more of them, but this is enough  to show that we can do some text
</p>
<hr />
<ul id="TheList" style="line-height:200%">
<li>
The first item in a list
</li>
<li style="color: red">
This is the second item
</li>
<li>
And this is a 
<a href="http://google.com">link</a>
to google
</li>
</ul>
</body>
</html>
```
Also see attached.

[doug.zip](https://github.com/UWPCE-PythonCert-ClassRepos/GP_Python210B_Winter_2019/files/2923606/doug.zip)

**Comment by Douglas-Klos** [comment]
Your output is only through test_html_output8.  The indentation is written to test_html_output9.

I'm not sure how to attach a zip file

```
<html>
Here is a paragraph of text -- there could be more of them, but this is enough to show that we can do some text
And here is another piece of text -- you should be able to add any number
</html>

<!DOCTYPE html>
<html>
<body>
<p>
Here is a paragraph of text -- there could be more of them, but this is enough to show that we can do some text
</p>
<p>
And here is another piece of text -- you should be able to add any number
</p>
</body>
</html>

<!DOCTYPE html>
<html>
<head>
<title>PythonClass = Revision 1087:</title>
</head>
<body>
<p>
Here is a paragraph of text -- there could be more of them, but this is enough to show that we can do some text
</p>
<p>
And here is another piece of text -- you should be able to add any number
</p>
</body>
</html>

<!DOCTYPE html>
<html>
<head>
<title>PythonClass = Revision 1087:</title>
</head>
<body>
<p style="text-align: center; font-style: oblique;">
Here is a paragraph of text -- there could be more of them, but this is enough to show that we can do some text
</p>
</body>
</html>

<!DOCTYPE html>
<html>
<head>
<title>PythonClass = Revision 1087:</title>
</head>
<body>
<p style="text-align: center; font-style: oblique;">
Here is a paragraph of text -- there could be more of them, but this is enough to show that we can do some text
</p>
<hr />
</body>
</html>

<!DOCTYPE html>
<html>
<head>
<title>PythonClass = Revision 1087:</title>
</head>
<body>
<p style="text-align: center; font-style: oblique;">
Here is a paragraph of text -- there could be more of them, but this is enough to show that we can do some text
</p>
<hr />
And this is a 
<a href="http://google.com">link</a>
to google
</body>
</html>

<!DOCTYPE html>
<html>
<head>
<title>PythonClass = Revision 1087:</title>
</head>
<body>
<h2>PythonClass - Class 6 example</h2>
<p style="text-align: center; font-style: oblique;">
Here is a paragraph of text -- there could be more of them, but this is enough to show that we can do some text
</p>
<hr />
<ul id="TheList" style="line-height:200%">
<li>
The first item in a list
</li>
<li style="color: red">
This is the second item
</li>
<li>
And this is a 
<a href="http://google.com">link</a>
to google
</li>
</ul>
</body>
</html>

<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8" />
<title>PythonClass = Revision 1087:</title>
</head>
<body>
<h2>PythonClass - Class 6 example</h2>
<p style="text-align: center; font-style: oblique;">
Here is a paragraph of text -- there could be more of them, but this is enough to show that we can do some text
</p>
<hr />
<ul id="TheList" style="line-height:200%">
<li>
The first item in a list
</li>
<li style="color: red">
This is the second item
</li>
<li>
And this is a
<a href="http://google.com">link</a>
to google
</li>
</ul>
</body>
</html>

<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <title>PythonClass = Revision 1087:</title>
    </head>
    <body>
        <h2>PythonClass - Class 6 example</h2>
        <p style="text-align: center; font-style: oblique;">
            Here is a paragraph of text -- there could be more of them, but this is enough to show that we can do some text
        </p>
        <hr />
        <ul id="TheList" style="line-height:200%">
            <li>
                The first item in a list
            </li>
            <li style="color: red">
                This is the second item
            </li>
            <li>
                And this is a
                <a href="http://google.com">link</a>
                to google
            </li>
        </ul>
    </body>
</html>

Execution time = 0.0011165142059326172
```

**Comment by Douglas-Klos** [comment]
The default run_html_render.py file given to us did not include any output for indentation, if that's the test you're running on it, I had to add an additional line to it to write a 9th file that includes indent.

`   render_page(page, "test_html_output9.html", "    ")`

**Comment by mdgregor** [comment]
Ahh, that makes sense then.  I"ll update your grade!

**Pull request merged**
